export { default as Dashboard } from './Dashboard';
export { default as Users} from './Users';
export { default as Sites} from './Sites';
export { default as Apartments} from './Apartments';
export { default as Flats} from './Flats';
export { default as Gates} from './Gates';
export { default as Cars} from './Cars';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgotPassword } from './ForgotPassword';
export { default as NotFound} from "./NotFound";
